[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
svm = "HFRNgEvcUTe7NTDvYXw9wa9sZCnukYGp3V8JuGf7fLND"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
